### ISSUE TITLE
Crash on SwiftUI project EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by clementprem** [johnno1962/HotReloading#3]
Injection keeps crashing on save 

![Screen Shot 2021-03-05 at 10 41 41 PM](https://user-images.githubusercontent.com/1575237/110176671-f7a94780-7e03-11eb-929b-9c7c1ef877d8.png)

**Comment by johnno1962** [comment]
Hi, are you using .eraseToAnyView() on all View properties?

**Comment by clementprem** [comment]
Hey yes, I used to work for some time, after I started adding complicated structures to the view it started to crash. I am closing this for now, because I am unable to test this beginning of the week.

**Comment by johnno1962** [comment]
This seems strange to me and I'm interested in perusing this further to see what the problem is. I've never had an injection of SwiftUI fail for a reason I didn't eventually work out what the problem was. Are you adding .eraseToAnyView to everything that returns "some View"? The Opaque type changeing due to adding an element this is the only thing I can think of that would cause a crash. Or perhaps you added new properties to a struct though this should have given you a warning. If you have the time I'd like to teamview this to get to the bottom of it!
